scriptpath='gui_aankoopkosten.pyw'
scriptname="Aankoopkosten"
scriptdesc="Berekent kosten aankoop huis"
scriptver="1.0"
scripticon="icon.ico"
scriptauthor="Mike Guilmot"
scriptcopyright="FreeWare"
scriptextraincludes=()
scriptpackages=[]
